<?php
/**
 * Modules manager extender: updatable icon in module principal data (before)
 *
 * @package    BardCanvas
 * @subpackage updates_client
 * @author     Alejandro Caballero - lava.caballero@gmail.com
 */
?>

<br><span class="framed_content inlined state_highlight updatable_span">
    <i class="fa fa-exclamation-circle"></i>
    <?= $this_module->language->modules_manager->new_version_found ?>
</span>
